import type { Config } from "tailwindcss";

const ap = (token: string) => `rgb(var(--ap-${token}) / <alpha-value>)`;

export default <Partial<Config>>{
  darkMode: "class",
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./app.vue",
  ],
  theme: {
    extend: {
      colors: {
        ui: {
          bg: "rgb(var(--ui-bg) / <alpha-value>)",
          surface: "rgb(var(--ui-surface) / <alpha-value>)",
          elevated: "rgb(var(--ui-elevated) / <alpha-value>)",
          border: "rgb(var(--ui-border) / <alpha-value>)",
          text: "rgb(var(--ui-text) / <alpha-value>)",
          muted: "rgb(var(--ui-muted) / <alpha-value>)",
        },
        background: ap("background"),
        surface: ap("surface"),
        "on-background": ap("on-background"),
        "on-surface": ap("on-surface"),
        "on-surface-variant": ap("on-surface-variant"),
        "pure-white": ap("pure-white"),
        "off-white": ap("off-white"),
        "deep-navy": ap("deep-navy"),
        "on-navy": ap("on-navy"),
        "electric-pink": ap("electric-pink"),
        "action-green": ap("action-green"),
        primary: ap("primary"),
        "on-primary": ap("on-primary"),
        "primary-container": ap("primary-container"),
        "on-primary-container": ap("on-primary-container"),
        "primary-fixed": ap("primary-fixed"),
        "primary-fixed-dim": ap("primary-fixed-dim"),
        secondary: ap("secondary"),
        "secondary-container": ap("secondary-container"),
        "secondary-fixed": ap("secondary-fixed"),
        "secondary-fixed-dim": ap("secondary-fixed-dim"),
        "on-secondary-container": ap("on-secondary-container"),
        error: ap("error"),
        "error-container": ap("error-container"),
        "on-error-container": ap("on-error-container"),
        outline: ap("outline"),
        "outline-variant": ap("outline-variant"),
        "surface-container": ap("surface-container"),
        "surface-container-low": ap("surface-container-low"),
        "surface-container-high": ap("surface-container-high"),
        "surface-container-highest": ap("surface-container-highest"),
        "surface-container-lowest": ap("surface-container-lowest"),
        "surface-tint": ap("surface-tint"),
        "surface-dim": ap("surface-dim"),
        "tertiary-container": ap("tertiary-container"),
        "tertiary-fixed": ap("tertiary-fixed"),
        "on-tertiary-fixed": ap("on-tertiary-fixed"),
      },
      maxWidth: {
        "container-max": "1280px",
      },
      spacing: {
        base: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "80px",
      },
      fontFamily: {
        "button-text": ['"Hanken Grotesk"', "sans-serif"],
        "headline-md": ['"Hanken Grotesk"', "sans-serif"],
        "headline-lg": ['"Hanken Grotesk"', "sans-serif"],
        "headline-lg-mobile": ['"Hanken Grotesk"', "sans-serif"],
        "display-lg": ['"Hanken Grotesk"', "sans-serif"],
        "label-caps": ['"JetBrains Mono"', "monospace"],
        "body-lg": ["Rubik", "sans-serif"],
        "body-md": ["Rubik", "sans-serif"],
      },
      fontSize: {
        "button-text": ["16px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
