// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/24/2026, 9:06:59 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Administrator/Desktop/project am working on/Lado/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/project am working on/Lado/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/project am working on/Lado/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/project am working on/Lado/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/project am working on/Lado/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Administrator/Desktop/project am working on/Lado/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Administrator/Desktop/project am working on/Lado/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Administrator/Desktop/project am working on/Lado/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/project am working on/Lado/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/project am working on/Lado/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/project am working on/Lado/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;